### ISSUE TITLE
Leaving the Game as the Current Player Breaks the Game

### ISSUE THREAD

**Issue by Kkoile** [soprafs20-group09/frantic-server#10]
When leaving the game (eg. by a page refresh) and being the active player, there is no one who is the next active player. So its nobodies turn and the current game can't be played further.
I would expect that it will be the turn of the next player counterclockwise.

**Comment by JaanWilli** [comment]
We will look into this, because yes, the game should continue with the next player. Were you playing with timers on or off?

**Comment by regloff** [comment]
Thanks @Kkoile for pointing this out. It was just a simple programming mistake ;-)
