### ISSUE TITLE
Suggestion: Make timer adjustable and optional.

### ISSUE THREAD

**Issue by flaviakim** [soprafs20-group09/frantic-server#2]
#### Description

Give the players the option in the lobby to _change the timer duration_ and to _disable the timer completely_

Optionally give the lobby owner the option to pause the timer, in case the group wants to take a break in a long game round, someone has to go to the toilet, etc..

#### Reasons

- Especially for people new to the game, the timer duration is extremely short.

- Additionally if a player's internet connection is slow (or the browser can't handle the animations that well *cough* safari *cough*), the player might even have way less time than 30 seconds to react.

- While the timer might be a good thing if the game ever picks up and is played between random people on the internet, I assume most of the people who play the game are friends/family. Often they also have a conversation while playing. The timer hinders the conversation as you have to concentrate much harder on the game, as you might otherwise miss your turn.

- Especially the timer between game rounds should be disabled and replaced by a "start new round" button. When ending a round, players might want to take a break for getting something to drink or whatever reason. The forced continuation of the next round makes the game extremely stressful.

**Comment by flaviakim** [comment]
(I'd also offer to help implement this)

**Comment by JaanWilli** [comment]
Yes, that is a good idea!
Just note that it is not exactly simple to implement, as our implementation relies heavily on these timers.
Therefore, if you want to take the lead on this one, feel free :) I can provide some assistance in that case. Otherwise we'll discuss it in the team.

**Comment by Davfon** [comment]
Hi cosycat, we discussed your feature request in the team and think it would be a great addition to the game. We will work on this feature in the upcoming time period. Thanks for your input. :) In case you already started and wanted to share some ideas, feel free to place them here.

**Comment by flaviakim** [comment]
My idea would be to just multiply each timer by a variable. And then add an option to set this variable in the lobby. (for the ui it could just display the actual time for a turn instead of the variable)

And an easy way to disable the timer without messing up everything that depends on it could be to just add a checkbox "disable timer" and it sets the variable to a really high value, so a turn would take days to finish. And then just don't show the timer. (of course this only works if everything in the game is "skippable" with an action/decision from the player(s)).

**Comment by regloff** [comment]
Feature is implemented #7
